# Generated by Django 4.0.5 on 2022-06-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_colaborador_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombreIn', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Cantidad', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
